# Generated by Django 5.2.3 on 2025-07-04 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('id_estudiante_institucional', models.CharField(max_length=50, unique=True)),
                ('programa_academico', models.CharField(max_length=150)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CredencialBlockchain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.PositiveIntegerField(blank=True, help_text='El ID del token NFT en la blockchain', null=True, unique=True)),
                ('direccion_wallet_alumno', models.CharField(help_text='Dirección de la wallet a la que se emitió', max_length=42)),
                ('tx_hash_emision', models.CharField(blank=True, help_text='Hash de la transacción de emisión', max_length=66, null=True, unique=True)),
                ('tx_hash_revocacion', models.CharField(blank=True, help_text='Hash de la transacción de revocación', max_length=66, null=True, unique=True)),
                ('metadata_json', models.JSONField(help_text='Copia del JSON de metadatos subido a IPFS')),
                ('metadata_cid', models.CharField(help_text='CID del archivo de metadatos en IPFS', max_length=100)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de emisión'), ('ACTIVA', 'Activa en Blockchain'), ('REVOCADA', 'Revocada'), ('ERROR', 'Error de emisión')], default='PENDIENTE', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credenciales', to='credenciales_app.alumno')),
            ],
            options={
                'verbose_name': 'Credencial Blockchain',
                'verbose_name_plural': 'Credenciales Blockchain',
            },
        ),
    ]
