# Generated by Django 5.2.3 on 2025-07-04 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credenciales_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credencialblockchain',
            name='notas_error',
            field=models.TextField(blank=True, help_text='Detalles del error si la emisión falla', null=True),
        ),
        migrations.AlterField(
            model_name='credencialblockchain',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de emisión'), ('EMITIDA', 'Emitida en Blockchain'), ('REVOCADA', 'Revocada'), ('ERROR', 'Error de emisión')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='credencialblockchain',
            name='metadata_json',
            field=models.JSONField(blank=True, help_text='Copia del JSON de metadatos subido a IPFS', null=True),
        ),
    ]
